import { Gym, Wall, Climb, Rating, Profile, ChallengeAttempt } from "@/types";

export const INITIAL_GYMS: Gym[] = [
  {
    id: "gym-1",
    name: "Summit Peak Climbing Gym",
    location: "Downtown Tech District",
    created_at: new Date(Date.now() - 90 * 24 * 3600 * 1000).toISOString(),
    wall_count: 3,
    climb_count: 5,
  },
  {
    id: "gym-2",
    name: "Gravity Lab Bouldering",
    location: "Westside Warehouse District",
    created_at: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
    wall_count: 2,
    climb_count: 4,
  },
  {
    id: "gym-3",
    name: "Crux & Co. Climbing Club",
    location: "Northside Campus Area",
    created_at: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
    wall_count: 2,
    climb_count: 3,
  }
];

export const INITIAL_WALLS: Wall[] = [
  {
    id: "wall-1",
    gym_id: "gym-1",
    name: "The Cave (45° Overhang)",
    description: "Heavy steep overhang for dynamic power moves and steep heel hooks.",
    created_at: new Date().toISOString(),
  },
  {
    id: "wall-2",
    gym_id: "gym-1",
    name: "Slab Paradise",
    description: "Low-angle balance, micro-crimps, and delicate footwork.",
    created_at: new Date().toISOString(),
  },
  {
    id: "wall-3",
    gym_id: "gym-1",
    name: "Island Bouldering Feature",
    description: "360-degree top-out boulder in the main pit.",
    created_at: new Date().toISOString(),
  },
  {
    id: "wall-4",
    gym_id: "gym-2",
    name: "Monolith Wall",
    description: "Vertical power-endurance feature with compression arêtes.",
    created_at: new Date().toISOString(),
  },
  {
    id: "wall-5",
    gym_id: "gym-2",
    name: "Roof Cavern",
    description: "Full horizontal ceiling roof climbs.",
    created_at: new Date().toISOString(),
  },
  {
    id: "wall-6",
    gym_id: "gym-3",
    name: "Comp Wall",
    description: "World Cup style coordination jumps and dual-texture volumes.",
    created_at: new Date().toISOString(),
  }
];

export const INITIAL_CLIMBS: Climb[] = [
  {
    id: "climb-1",
    gym_id: "gym-1",
    wall_id: "wall-1",
    name: "Pink Panther Crimp",
    color: "Pink",
    discipline: "bouldering",
    gym_grade: "V4",
    setter_notes: "Technical crimps on the 45 degree overhang. Watch out for the match on hold #4.",
    active_from: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString().split('T')[0],
    is_active: true,
    qr_code_token: "pink-panther-v4",
    created_at: new Date().toISOString(),
    gym_name: "Summit Peak Climbing Gym",
    wall_name: "The Cave (45° Overhang)",
  },
  {
    id: "climb-2",
    gym_id: "gym-1",
    wall_id: "wall-1",
    name: "Subzero Slopers",
    color: "Blue",
    discipline: "bouldering",
    gym_grade: "V6",
    setter_notes: "Compression slopers requiring high core tension and precise heel hooks.",
    active_from: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString().split('T')[0],
    is_active: true,
    qr_code_token: "subzero-slopers-v6",
    created_at: new Date().toISOString(),
    gym_name: "Summit Peak Climbing Gym",
    wall_name: "The Cave (45° Overhang)",
  },
  {
    id: "climb-3",
    gym_id: "gym-1",
    wall_id: "wall-2",
    name: "Balance Beam Ballet",
    color: "Yellow",
    discipline: "bouldering",
    gym_grade: "V3",
    setter_notes: "No hands rest in the middle if you trust your smear!",
    active_from: new Date(Date.now() - 20 * 24 * 3600 * 1000).toISOString().split('T')[0],
    is_active: true,
    qr_code_token: "balance-beam-v3",
    created_at: new Date().toISOString(),
    gym_name: "Summit Peak Climbing Gym",
    wall_name: "Slab Paradise",
  },
  {
    id: "climb-4",
    gym_id: "gym-2",
    wall_id: "wall-4",
    name: "Gravity Monarch",
    color: "Black",
    discipline: "bouldering",
    gym_grade: "V4",
    setter_notes: "Big double-clutch dyno across the volume gap.",
    active_from: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString().split('T')[0],
    is_active: true,
    qr_code_token: "gravity-monarch-v4",
    created_at: new Date().toISOString(),
    gym_name: "Gravity Lab Bouldering",
    wall_name: "Monolith Wall",
  },
  {
    id: "climb-5",
    gym_id: "gym-2",
    wall_id: "wall-5",
    name: "Bat Hang Blast",
    color: "Green",
    discipline: "bouldering",
    gym_grade: "V5",
    setter_notes: "Optional bat-hang start on the roof lip.",
    active_from: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString().split('T')[0],
    is_active: true,
    qr_code_token: "bat-hang-v5",
    created_at: new Date().toISOString(),
    gym_name: "Gravity Lab Bouldering",
    wall_name: "Roof Cavern",
  },
  {
    id: "climb-6",
    gym_id: "gym-3",
    wall_id: "wall-6",
    name: "Comp World Paddle",
    color: "Red",
    discipline: "bouldering",
    gym_grade: "V5",
    setter_notes: "Three-step dynamic paddle dyno.",
    active_from: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString().split('T')[0],
    is_active: true,
    qr_code_token: "comp-world-paddle-v5",
    created_at: new Date().toISOString(),
    gym_name: "Crux & Co. Climbing Club",
    wall_name: "Comp Wall",
  }
];

export const INITIAL_RATINGS: Rating[] = [
  // Ratings for climb 1 (Summit Peak Pink Panther V4)
  {
    id: "r-1",
    climb_id: "climb-1",
    user_id: "user-alex",
    user_display_name: "Alex C.",
    comparative_rating: "harder",
    quality_stars: 5,
    comment: "Super technical! The crux crimp feels much sharper than a standard V4, definitely felt like a solid V5.",
    is_spam: false,
    created_at: new Date(Date.now() - 12 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "r-2",
    climb_id: "climb-1",
    user_id: "user-sam",
    user_display_name: "Sam K.",
    comparative_rating: "harder",
    quality_stars: 4,
    comment: "Summit Peak always sets soft, but this specific climb is stiff! Feels harder than graded.",
    is_spam: false,
    created_at: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "r-3",
    climb_id: "climb-1",
    user_id: "user-jordan",
    user_display_name: "Jordan P.",
    comparative_rating: "as_graded",
    quality_stars: 4,
    comment: "Morpho route! If you have reach, it's V4, shorter climbers might find it harder.",
    is_spam: false,
    created_at: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
  },

  // Ratings for climb 2 (Summit Peak Subzero Slopers V6)
  {
    id: "r-4",
    climb_id: "climb-2",
    user_id: "user-alex",
    user_display_name: "Alex C.",
    comparative_rating: "easier",
    quality_stars: 4,
    comment: "Great slopers with fresh friction. With the right heel hook it feels like V5.",
    is_spam: false,
    created_at: new Date(Date.now() - 9 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "r-5",
    climb_id: "climb-2",
    user_id: "user-taylor",
    user_display_name: "Taylor M.",
    comparative_rating: "easier",
    quality_stars: 5,
    comment: "Soft V6 grade for sure! Super fun compression aesthetic.",
    is_spam: false,
    created_at: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
  },

  // Ratings for climb 4 (Gravity Lab Monarch V4)
  {
    id: "r-6",
    climb_id: "climb-4",
    user_id: "user-alex", // Multi-gym user!
    user_display_name: "Alex C.",
    comparative_rating: "harder",
    quality_stars: 5,
    comment: "Gravity Lab grades are so stiff compared to Summit Peak! This V4 dyno would easily be a V5 or V6 at Summit Peak.",
    is_spam: false,
    created_at: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "r-7",
    climb_id: "climb-4",
    user_id: "user-morgan",
    user_display_name: "Morgan B.",
    comparative_rating: "harder",
    quality_stars: 4,
    comment: "Big commit move! Stiff for a V4.",
    is_spam: false,
    created_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
  },

  // Ratings for climb 6 (Crux & Co. Comp World V5)
  {
    id: "r-8",
    climb_id: "climb-6",
    user_id: "user-sam", // Multi-gym user!
    user_display_name: "Sam K.",
    comparative_rating: "as_graded",
    quality_stars: 5,
    comment: "Spot-on World Cup style setting. Fun coordination move!",
    is_spam: false,
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  }
];

export const INITIAL_CHALLENGE_ATTEMPTS: ChallengeAttempt[] = [
  {
    id: "challenge-1",
    climb_id: "climb-1",
    user_id: "user-alex",
    user_display_name: "Alex C.",
    challenge_type: "speed",
    value: 31,
    created_at: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "challenge-2",
    climb_id: "climb-1",
    user_id: "user-sam",
    user_display_name: "Sam K.",
    challenge_type: "speed",
    value: 38,
    created_at: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "challenge-3",
    climb_id: "climb-1",
    user_id: "user-morgan",
    user_display_name: "Morgan B.",
    challenge_type: "fewest_holds",
    value: 12,
    created_at: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "challenge-4",
    climb_id: "climb-4",
    user_id: "user-sam",
    user_display_name: "Sam K.",
    challenge_type: "speed",
    value: 44,
    created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "challenge-5",
    climb_id: "climb-4",
    user_id: "user-alex",
    user_display_name: "Alex C.",
    challenge_type: "fewest_holds",
    value: 15,
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
];

export const INITIAL_PROFILES: Profile[] = [
  {
    id: "user-alex",
    email: "alex@climber.org",
    display_name: "Alex C.",
    role: "owner",
    home_gym_id: "gym-1",
    created_at: new Date().toISOString(),
  },
  {
    id: "user-sam",
    email: "sam@climber.org",
    display_name: "Sam K.",
    role: "climber",
    home_gym_id: "gym-1",
    created_at: new Date().toISOString(),
  },
  {
    id: "user-jordan",
    email: "jordan@climber.org",
    display_name: "Jordan P.",
    role: "climber",
    home_gym_id: "gym-2",
    created_at: new Date().toISOString(),
  }
];
